name: build-and-test-server
run-name: ${{ github.actor }} is building and testing server
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.21.x' ]
    services:
      postgres:

        image : postgres
        
        env:
          POSTGRES_PASSWORD: postgres
        
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: go get -u -d ./...
      - name: List files in directory
        run: ls -l
      - name: Running healthz integration test
        run: |
          cd ./cmd/app
          ls -l
          go test -run TestIntegreationHealthz
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: csye6225
        

