name: build-and-test-server
run-name: ${{ github.actor }} is building and testing server
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:

        image : postgres
        
        env:
          POSTGRES_PASSWORD: postgres
        
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Echo Hello World to console
        run: echo "Hello World"
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: csye6225
        

