name: build-and-test-server
run-name: ${{ github.actor }} is building and testing server
on:
  pull_request:
    branches:
      - main
      - development
jobs:
  run-integration-test:
    runs-on: ubuntu-latest
    name: run-integration-test
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.1
      - name: Display Go version
        run: go version
      - name: Install dependencies
        run: go get -u -d ./...
      - name: Make the script files executable
        run: chmod +x install_db.sh
      - name: Run shell script to setup database
        run: ./install_db.sh
        env:
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
      - name: Running healthz integration test
        run: |
          cd ./cmd/app
          ls -l
          go test -run TestIntegreationHealthz
        env:
          POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
        

