name: validate-packer

on:
  pull_request:
    branches:
      - main
      - development
env:
  PRODUCT_VERSION: "latest"

jobs:
  validate-packer:
    runs-on: ubuntu-latest
    name: packer-validate
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        run: "packer init ."

      - name: Run `packer fmt`
        run: "packer fmt -check ."

      - name: Dummy artifact for validation
        run: "sudo touch app.zip"

      - name: Run `packer validate`
        run: "packer validate ."
        env:
          PKR_VAR_aws_region: ${{ vars.AWS_REGION }}
          PKR_VAR_source_ami_id: ${{ vars.SOURCE_AMI_ID }}
          PKR_VAR_ssh_username: ${{ secrets.SSH_USERNAME }}
          PKR_VAR_dev_subnet_id: ${{ vars.DEV_SUBNET_ID }}
          PKR_VAR_linux_group: ${{ vars.LINUX_GROUP }}
          PKR_VAR_linux_user: ${{ vars.LINUX_USER }}
          PKR_VAR_user_home_dir: ${{ vars.USER_HOME_DIR }}
          PKR_VAR_account_csv_path: ${{ vars.ACCOUNT_CSV_PATH }}
